[2024-05-13T21:32:17.788+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-13T21:32:17.831+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:22:36.910924+00:00 [queued]>
[2024-05-13T21:32:17.847+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:22:36.910924+00:00 [queued]>
[2024-05-13T21:32:17.849+0000] {taskinstance.py:2303} INFO - Starting attempt 9 of 10
[2024-05-13T21:32:17.880+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file_to_gcs> on 2024-05-13 20:22:36.910924+00:00
[2024-05-13T21:32:17.898+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=153) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-13T21:32:17.904+0000] {standard_task_runner.py:63} INFO - Started process 165 to run task
[2024-05-13T21:32:17.901+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'gcs_upload_example', 'upload_file_to_gcs', 'manual__2024-05-13T20:22:36.910924+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/gcp_example.py', '--cfg-path', '/tmp/tmpd56g3o_r']
[2024-05-13T21:32:17.913+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask upload_file_to_gcs
[2024-05-13T21:32:17.946+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-05-13T21:32:18.051+0000] {task_command.py:426} INFO - Running <TaskInstance: gcs_upload_example.upload_file_to_gcs manual__2024-05-13T20:22:36.910924+00:00 [running]> on host 9df925c47a8b
[2024-05-13T21:32:18.367+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_upload_example' AIRFLOW_CTX_TASK_ID='upload_file_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-05-13T20:22:36.910924+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-13T20:22:36.910924+00:00'
[2024-05-13T21:32:18.372+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-13T21:32:18.500+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-05-13T21:32:18.504+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-05-13T21:32:18.506+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-13T21:32:18.507+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 97, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: ./lesson_10/data/sales_clean.csv
[2024-05-13T21:32:18.551+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_upload_example, task_id=upload_file_to_gcs, execution_date=20240513T202236, start_date=20240513T213217, end_date=20240513T213218
[2024-05-13T21:32:18.584+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task upload_file_to_gcs (./lesson_10/data/sales_clean.csv; 165)
[2024-05-13T21:32:18.622+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-13T21:32:18.666+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-13T21:32:18.671+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
