[2024-05-15T20:20:47.939+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-20T00:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-05-15T21:01:33.967+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: upload_csv_to_gcs_bucket.upload_task_0 scheduled__2022-08-20T00:00:00+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
